// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c068d930-72d0-4771-a6e1-891e89359fa5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Q0dpHXXHR",
    "aws_user_pools_web_client_id": "1eu2b5j73ei8vkrer09lk9eiuo",
    "oauth": {
        "domain": "gohomenotes-test-test.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:9000/",
        "redirectSignOut": "http://localhost:9000/",
        "responseType": "implicit"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
