// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:948ec307-7f8c-45f0-b42c-2a358ce030ab",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_T9gIPUK9i",
    "aws_user_pools_web_client_id": "2s7us162o5s41ho8b62am68nen",
    "oauth": {
        "domain": "gohomenotes3-10-20-2019-poc.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:9000/",
        "redirectSignOut": "http://localhost:9000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
